apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx # routes all traffic when type is LoadBalancer to all pods that have the tag in this location
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80